name = "days-counter-pro"
pages_build_output_dir = "dist"

[build]
command = "npm run build"
cwd = "."

[env.production]
name = "days-counter-pro-prod"
routes = [{ pattern = "daycounterpro.com", zone_name = "daycounterpro.com" }]
